<?php

namespace Debjyotikar001\AssetOptimise\Console;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

class ClearMinifiedAssets extends Command
{
  /**
   * The name and signature of the console command.
   *
   * asset-optimise:clear-minified {type?}
   */
  protected $signature = 'asset-optimise:clear-minified {type? : css | js}';

  /**
   * The console command description.
   */
  protected $description = 'Clear minified asset files (css, js, or all) generated by AssetOptimise';

  /**
   * Execute the console command.
   */
  public function handle(): int
  {
    $type = $this->argument('type');

    $basePath = storage_path('app/public/minified');

    // Determine target paths
    if ($type === null) {
      $path = $basePath;
      $label = 'minified assets';
    } elseif (in_array($type, ['css', 'js'], true)) {
      $path = $basePath . DIRECTORY_SEPARATOR . $type;
      $label = "minified {$type} assets";
    } else {
      $this->error('Invalid option. Allowed values: css, js');
      return self::FAILURE;
    }

    if (!is_dir($path)) {
      $this->info("No {$label} directory found. Nothing to clean.");
      return self::SUCCESS;
    }

    File::cleanDirectory($path);

    $this->info("Successfully cleared {$label}.");

    return self::SUCCESS;
  }
}
